FROM quay.io/openstack-k8s-operators/rhosp17-openstack-tripleoclient:17.0_20210720.1

USER root
RUN dnf -y install patch
RUN dnf -y clean all

# https://review.opendev.org/c/openstack/tripleo-common/+/803599
ADD 0001-inventory.py-all_get_neutron_data-to-handle-404.patch /root/
RUN patch -p1 < /root/0001-inventory.py-all_get_neutron_data-to-handle-404.patch -d /usr/lib/python3.6/site-packages/

# https://bugs.launchpad.net/tripleo/+bug/1939167
ADD 0001-Fix-cell-export-no-attribute-exception.patch /root/
RUN patch -p1 < /root/0001-Fix-cell-export-no-attribute-exception.patch -d /usr/lib/python3.6/site-packages/

USER cloud-admin
