---
openstackclient_networks:
  - ctlplane
  - external
  - internal_api
  - internal_api_leaf1

enable_freeipa: true
osp_release_defaults:
  tlse: true
  networks: ipv6_subnet
  vmset:
    Controller:
      # Reset default Controller roleCount to 0
      count: 0
    CtlNovaStdalone:
      count: 1
      cores: 6
      memory: 20
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
    Novacontrol:
      count: 1
      cores: 2
      memory: 10
      networks:
        - ctlplane
        - internal_api
        - storage
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
  bmset:
    Compute:
      count: 0
    ComputeHCILeaf1:
      count: 1
      ctlplane_interface: enp1s0
      networks:
        - ctlplane
        - internal_api_leaf1
        - tenant_leaf1
        - storage_leaf1
        - storage_mgmt_leaf1
    ComputeHCILeaf2:
      count: 1
      ctlplane_interface: enp1s0
      networks:
        - ctlplane
        - internal_api_leaf2
        - tenant_leaf2
        - storage_leaf2
        - storage_mgmt_leaf2
  extrafeatures:
  - hci
  - ipv6

tempest_enable_feature_dict:
  network:
    # The cidr block to allocate project ipv6 subnets from (string value)
    project_network_v6_cidr: 2001:db8:fd01::/48
  compute-feature-enabled:
    vnc_console: true
    live_migration: true
    block_migration_for_live_migration: false
    volume_backed_live_migration: true
    console_output: true
