---
openstackclient_networks:
  - ctlplane
  - external
  - internal_api

enable_fencing: true

ocp_num_workers: 0
ocp_master_memory: 80000
ocp_master_vcpu: 24
ocp_master_disk: 100

osp_release_defaults:
  networks: ipv4_subnet
  vmset:
    Controller:
      count: 0    
    ControllerSriov:
      count: 3
      cores: 6
      memory: 20
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
  # OSP compute OCP worker settings
  bmset:
    Compute:
        # number of OCP worker nodes should be OSP compute hosts
        count: 0
    ComputeSriov:
      # number of OCP worker nodes should be OSP compute hosts
      count: 2
      ctlplane_interface: ens1f2
      networks:
        - ctlplane
        - internal_api
        - tenant
        - storage
  # number of OSD disks per compute node
  ceph_osd_disks:
    - sdb
    - sdc
  # size of OSD disk size in GB
  ceph_num_osd_disk_size: 20
  domain_name: "osptest.{{ base_domain_name }}"
  dns_servers:
    - 172.22.0.1
  dns_search_domains:
    - "osptest.{{ base_domain_name }}"
    - "{{ base_domain_name }}"
  attach_configs:
    br-ctlplane:
      interfaces:
      - type: bridge
        name: br-ctlplane
        interface: enp1s0
        dhcp: true
        mtu: 1500
    br-osp:
      interfaces:
      - type: bridge
        name: br-osp
        interface: enp7s0
        mtu: 9000
      - type: ethernet
        interface: enp7s0
        mtu: 9000
    br-ex:
      interfaces:
      - type: bridge
        name: br-ex
        interface: enp6s0
        mtu: 1500
  networks: ipv4_hybrid
  extrafeatures:
        - nfv_sriov
  ovn_bridge_mac_mappings:
    phys_networks:
    - name: datacentre
      prefix: fa:16:3a
    - name: datacentre2
      prefix: fa:16:3b

