osp_release_defaults:
  bmset:
    ComputeHCI:
      count: 2
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
  extrafeatures:
    - hci
