---
openstackclient_networks:
  - ctlplane
  - external
  - internal_api
  - internal_api_leaf1

enable_freeipa: true
osp_release_defaults:
  tlse: true
  networks: ipv6_subnet
  vmset:
    Controller:
      count: 1
      cores: 6
      disk_size: 40
      memory: 20
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      storage_class: host-nfs-storageclass
  bmset:
    Compute:
      count: 0
    ComputeHCILeaf1:
      count: 1
      ctlplane_interface: enp1s0
      networks:
        - ctlplane
        - internal_api_leaf1
        - storage_leaf1
        - storage_mgmt_leaf1
        - tenant_leaf1
    ComputeHCILeaf2:
      count: 1
      ctlplane_interface: enp1s0
      networks:
        - ctlplane
        - internal_api_leaf2
        - storage_leaf2
        - storage_mgmt_leaf2
        - tenant_leaf2
  extrafeatures:
  - hci
  - ipv6

# phase2 tempest tests
tempest_test_dict:
  regex: '(?!.*\[.*\bslow\b.*\])(^tempest\.(api|scenario))'
  includelist: []
  # per default with OVN there is no DHCPAgent, disable the tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON tests
  excludelist:
      - "^tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate"
      - "^tempest.api.compute.admin.test_live_migration.LiveMigrationTest.test_live_block_migration_paused"
      - "^tempest.api.compute.admin.test_live_migration.LiveAutoBlockMigrationV225Test.test_live_block_migration_paused"
      - "^tempest.api.compute.admin.test_live_migration.LiveMigrationRemoteConsolesV26Test.test_live_block_migration_paused"
      - "^tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_add_remove_network_from_dhcp_agent"
      - "^tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_list_networks_hosted_by_one_dhcp"

tempest_enable_feature_dict:
  network:
    # The cidr block to allocate project ipv6 subnets from (string value)
    project_network_v6_cidr: 2001:db8:fd00:6000::/64
    # The mask bits for project ipv6 subnets (integer value)
    project_network_v6_mask_bits: 64
  network-feature-enabled:
    ipv6: true
    # with ipv6 only external network there are no floating ips
    floating_ips: false
  compute-feature-enabled:
    vnc_console: true
    live_migration: true
    block_migration_for_live_migration: true
    volume_backed_live_migration: true
    console_output: true
