osp_release_defaults:
  networks: ipv6_subnet
  extrafeatures:
    - ipv6
    - hci
  bmset:
    Compute:
      count: 0
    ComputeHCI:
      count: 2
      ctlplane_interface: enp1s0
      networks:
        - ctlplane
        - internal_api
        - tenant
        - storage
        - storage_mgmt

# TODO: create good set of ipv6 tempest tests, right now disabled those which create floating IP, which is not the case in IPv6
tempest_test_dict:
  regex: ''
  includelist:
      - "tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern"
      - "tempest.scenario.test_minimum_basic.TestMinimumBasicScenario"
      - "tempest.scenario.test_network_basic_ops.TestNetworkBasicOps"
      - "tempest.scenario.test_snapshot_pattern.TestSnapshotPattern"
  # per default with OVN there is no DHCPAgent, disable the tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON tests
  excludelist:
      - "^tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_port_security_macspoofing_port"
      - "^tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_add_remove_network_from_dhcp_agent"
      - "^tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_list_networks_hosted_by_one_dhcp"
      - "^tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario"
      - "^tempest.scenario.test_snapshot_pattern.TestSnapshotPattern.test_snapshot_pattern"
      - "^tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_volume_boot_pattern"

tempest_enable_feature_dict:
  network:
    # The cidr block to allocate project ipv6 subnets from (string value)
    project_network_v6_cidr: 2001:db8:fd01::/48
  compute-feature-enabled:
    vnc_console: true
    live_migration: true
    block_migration_for_live_migration: false
    volume_backed_live_migration: true
    console_output: true
  network-feature-enabled:
    floating_ips: false
