openstackclient_image: registry.redhat.io/rhosp-rhel8/openstack-tripleoclient:16.2
osp_rhos_release_compose: passed_phase2
osp:
  release: 16.2
  # OSP controller VM sizing
  controller:
    count: 1
    cores: 6
    memory: 20
    disk_size: 40
    image_url_path: brewroot/packages/rhel-guest-image/8.4/1168/images/rhel-guest-image-8.4-1168.x86_64.qcow2
    storage_class: host-nfs-storageclass
  # OSP compute OCP worker settings
  compute:
    # number of OCP worker nodes should be OSP compute hosts
    count: 2
    # if false nfs is used for glance
    hci: false
    # number of OSD disks per compute node
    ceph_osd_disks:
      - sdb
      - sdc
    # size of OSD disk size in GB
    ceph_num_osd_disk_size: 20
  interface:
    external: enp6s0
    ospnetwork: enp7s0
  network_type: vlan
  container_tag: 16.2_20210901.2
  ceph_image: rhceph
  ceph_tag: 5-12
  # OSP deployment timeout
  deploy_timeout: 60m
