---
csv_version: latest-17.0
osp_release_auto_version: 17.0-RHEL-9
osp_release_auto_compose: passed_phase2
osp_release_defaults:
  base_image_url: https://download.devel.redhat.com/rhel-9/rel-eng/RHEL-9/latest-RHEL-9.0.0/compose/BaseOS/x86_64/images/rhel-guest-image-9.0-20220420.0.x86_64.qcow2
  bmset:
    Compute:
      count: 0
    ComputeHCI:
      count: 2
      ctlplane_interface: enp7s0
      networks:
        - ctlplane
        - internal_api
        - tenant
        - storage
        - storage_mgmt
  extrafeatures:
    - hci

ephemeral_heat:
  heat_api_image: "{{ registry_proxy }}/rh-osbs/rhosp17-openstack-heat-api:{{ osp_release_auto.tag }}"
  heat_engine_image: "{{ registry_proxy }}/rh-osbs/rhosp17-openstack-heat-engine:{{ osp_release_auto.tag }}"
  mariadb_image: "{{ registry_proxy }}/rh-osbs/rhosp17-openstack-mariadb:{{ osp_release_auto.tag }}"
  rabbit_image: "{{ registry_proxy }}/rh-osbs/rhosp17-openstack-rabbitmq:{{ osp_release_auto.tag }}"

