---
enable_fencing: true
csv_version: latest-17.1
osp_release_auto_version: 17.1-RHEL-9
osp_release_auto_compose: passed_phase1

# (mschuppert) can be deleted when released
openstackclient_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-tripleoclient:{{ osp_release_auto.tag }}"

ephemeral_heat:
  heat_api_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-heat-api:{{ osp_release_auto.tag }}"
  heat_engine_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-heat-engine:{{ osp_release_auto.tag }}"
  mariadb_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-mariadb:{{ osp_release_auto.tag }}"
  rabbit_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-rabbitmq:{{ osp_release_auto.tag }}"


openstackclient_networks:
  - ctlplane
  - external
  - internal_api

ocp_num_workers: 0
ocp_master_memory: 40000
ocp_master_vcpu: 12
ocp_master_disk: 100

osp_release_defaults:
  base_image_url: http://download.devel.redhat.com/brewroot/packages/rhel-guest-image/9.2/20230414.43/images/rhel-guest-image-9.2-20230414.43.x86_64.qcow2
  networks: ipv4_subnet
  vmset:
    Controller:
      count: 0
    ControllerSriov:
      count: 3
      cores: 6
      memory: 20
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
      additional_disks:
        - name: datadisk
          disk_size: 1
          storage_class: host-nfs-storageclass
          storage_access_mode: ReadWriteMany
          storage_volume_mode: Filesystem

  # OSP compute OCP worker settings
  bmset:
    Compute:
        # number of OCP worker nodes should be OSP compute hosts
        count: 0
    ComputeOvsDpdkSriov:
      # number of OCP worker nodes should be OSP compute hosts
      count: 2
      ctlplane_interface: ens1f2
      networks:
        - ctlplane
        - internal_api
        - tenant
        - storage
  # number of OSD disks per compute node
  ceph_osd_disks:
    - sdb
    - sdc
  # size of OSD disk size in GB
  ceph_num_osd_disk_size: 20
  domain_name: "osptest.{{ base_domain_name }}"
  dns_servers:
    - 172.22.0.1
  dns_search_domains:
    - "osptest.{{ base_domain_name }}"
    - "{{ base_domain_name }}"
  attach_configs:
    br-ctlplane:
      interfaces:
      - type: bridge
        name: br-ctlplane
        interface: enp1s0
        dhcp: true
        mtu: 1500
    br-osp:
      interfaces:
      - type: bridge
        name: br-osp
        interface: enp7s0
        mtu: 9000
      - type: ethernet
        interface: enp7s0
        mtu: 9000
    br-ex:
      interfaces:
      - type: bridge
        name: br-ex
        interface: enp6s0
        mtu: 1500
  networks: ipv4_hybrid
  extrafeatures:
        - nfv_dpdk_sriov
  ovn_bridge_mac_mappings:
    phys_networks:
    - name: datacentre
      prefix: fa:16:3a
    - name: datacentre2
      prefix: fa:16:3b
