---
csv_version: latest-17.1
osp_release_auto_version: 17.1-RHEL-9
osp_release_auto_compose: passed_phase1

osp_release_defaults:
  base_image_url: https://download.devel.redhat.com/rhel-9/rel-eng/RHEL-9/latest-RHEL-9.2.0/compose/BaseOS/x86_64/images/rhel-guest-image-9.2-20230414.17.x86_64.qcow2
  bmset:
    Compute:
      count: 0
    ComputeHCI:
      count: 2
      ctlplane_interface: enp7s0
      networks:
        - ctlplane
        - internal_api
        - tenant
        - storage
        - storage_mgmt
  extrafeatures:
    - hci

osp_extra_env_files:
  - metrics/ceilometer-write-qdr.yaml
  - metrics/qdr-edge-only.yaml

# (mschuppert) can be deleted when released
openstackclient_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-tripleoclient:{{ osp_release_auto.tag }}"

ephemeral_heat:
  heat_api_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-heat-api:{{ osp_release_auto.tag }}"
  heat_engine_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-heat-engine:{{ osp_release_auto.tag }}"
  mariadb_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-mariadb:{{ osp_release_auto.tag }}"
  rabbit_image: "rhos-qe-mirror-rdu2.usersys.redhat.com:5002/rh-osbs/rhosp17-openstack-rabbitmq:{{ osp_release_auto.tag }}"
