---
csv_version: latest-17.1
osp_release_auto_version: 17.1-RHEL-9


openstackclient_networks:
  - ctlplane
  - external
  - internal_api
  - internal_api_leaf1

osp_release_defaults:
  base_image_url: https://download.devel.redhat.com/rhel-9/rel-eng/RHEL-9/latest-RHEL-9.2.0/compose/BaseOS/x86_64/images/rhel-guest-image-9.2-20230414.17.x86_64.qcow2
  networks: ipv4_subnet
  vmset:
    Controller:
      count: 1
      cores: 6
      memory: 20
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
  bmset:
    Compute:
      count: 0
    ComputeHCILeaf1:
      count: 2
      ctlplane_interface: enp7s0
      networks:
        - ctlplane
        - internal_api_leaf1
        - storage_leaf1
        - storage_mgmt_leaf1
        - tenant_leaf1
  extrafeatures:
    - hci

# phase2 tempest tests
tempest_test_dict:
  regex: '(?!.*\[.*\bslow\b.*\])(^tempest\.(api|scenario))'
  includelist: []
  # per default with OVN there is no DHCPAgent, disable the tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON tests
  excludelist:
      - "^tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate"
      - "^tempest.api.compute.admin.test_live_migration.LiveMigrationTest.test_live_block_migration_paused"
      - "^tempest.api.compute.admin.test_live_migration.LiveAutoBlockMigrationV225Test.test_live_block_migration_paused"
      - "^tempest.api.compute.admin.test_live_migration.LiveMigrationRemoteConsolesV26Test.test_live_block_migration_paused"
      - "^tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_add_remove_network_from_dhcp_agent"
      - "^tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON.test_list_networks_hosted_by_one_dhcp"
      - "^tempest.api.compute.admin.test_live_migration.LiveMigrationTest.test_live_migration_with_trunk"
      - "^tempest.api.volume.admin.test_volume_types.VolumeTypesTest.test_volume_crud_with_volume_type_and_extra_specs"
      - "^tempest.api.volume.test_volume_delete_cascade.VolumesDeleteCascade.test_volume_from_snapshot_cascade_delete"

# disable block_migration_for_live_migration: false
tempest_enable_feature_dict:
  compute-feature-enabled:
    vnc_console: true
    live_migration: true
    block_migration_for_live_migration: false
    volume_backed_live_migration: true
    console_output: true

# (mschuppert) can be deleted when released
openstackclient_image: "{{ registry_proxy }}/rh-osbs/rhosp17-openstack-tripleoclient:{{ osp_release_auto.tag }}"

ephemeral_heat:
  heat_api_image: "{{ registry_proxy }}/rh-osbs/rhosp17-openstack-heat-api:{{ osp_release_auto.tag }}"
  heat_engine_image: "{{ registry_proxy }}/rh-osbs/rhosp17-openstack-heat-engine:{{ osp_release_auto.tag }}"
  mariadb_image: "{{ registry_proxy }}/rh-osbs/rhosp17-openstack-mariadb:{{ osp_release_auto.tag }}"
  rabbit_image: "{{ registry_proxy }}/rh-osbs/rhosp17-openstack-rabbitmq:{{ osp_release_auto.tag }}"
