---
csv_version: latest-17.1
osp_release_auto_version: 17.1-RHEL-9

osp_release_defaults:
  base_image_url:
    https://download.devel.redhat.com/rhel-9/rel-eng/RHEL-9/latest-RHEL-9.2.0/compose/BaseOS/x86_64/images/rhel-guest-image-9.2-20230414.17.x86_64.qcow2
  bmset:
    Compute:
      count: 0
    ComputeHCI:
      count: 2
      ctlplane_interface: enp7s0
      networks:
        - ctlplane
        - internal_api
        - tenant
        - storage
        - storage_mgmt
  extrafeatures:
    - hci

# (mschuppert) can be deleted when released
openstackclient_image: "registry.stage.redhat.io/rhosp-rhel9/openstack-tripleoclient:{{ osp_release_auto.tag }}"

ephemeral_heat:
  heat_api_image: "registry.stage.redhat.io/rhosp-rhel9/openstack-heat-api:{{ osp_release_auto.tag }}"
  heat_engine_image: "registry.stage.redhat.io/rhosp-rhel9/openstack-heat-engine:{{ osp_release_auto.tag }}"
  mariadb_image: "registry.stage.redhat.io/rhosp-rhel9/openstack-mariadb:{{ osp_release_auto.tag }}"
  rabbit_image: "registry.stage.redhat.io/rhosp-rhel9/openstack-rabbitmq:{{ osp_release_auto.tag }}"
