---
osp_networks:
  ctlplane:
    name: Control
    name_lower: ctlplane
    is_control_plane: true
    subnets:
    - name: ctlplane
      ipv4:
        cidr: 172.22.0.0/24
        gateway: 172.22.0.1
        allocation:
          start: 172.22.0.100
          end: 172.22.0.254
        routes:
        - destination: 172.22.1.0/24
          nexthop: 172.22.0.1
        - destination: 172.22.2.0/24
          nexthop: 172.22.0.1
      attach_config: br-ctlplane
    - name: ctlplane_leaf1
      ipv4:
        cidr: 172.22.1.0/24
        gateway: 172.22.1.1
        allocation:
          start: 172.22.1.100
          end: 172.22.1.254
        routes:
        - destination: 172.22.0.0/24
          nexthop: 172.22.1.1
        - destination: 172.22.2.0/24
          nexthop: 172.22.1.1
      attach_config: br-ctlplane
    - name: ctlplane_leaf2
      ipv4:
        cidr: 172.22.2.0/24
        gateway: 172.22.2.1
        allocation:
          start: 172.22.2.100
          end: 172.22.2.254
        routes:
        - destination: 172.22.0.0/24
          nexthop: 172.22.2.1
        - destination: 172.22.1.0/24
          nexthop: 172.22.2.1
      attach_config: br-ctlplane
  external:
    name: External
    name_lower: external
    subnets:
    - name: external
      ipv4:
        cidr: 10.0.0.0/24
        gateway: 10.0.0.1
        allocation:
          start: 10.0.0.10
          end: 10.0.0.250
      attach_config: br-ex
  internalapi:
    name: InternalApi
    name_lower: internal_api
    subnets:
    - name: internal_api
      vlan: 20
      ipv4:
        cidr: 172.17.0.0/24
        allocation:
          start: 172.17.0.10
          end: 172.17.0.250
        gateway: 172.17.0.1
        routes:
        - destination: 172.17.1.0/24
          nexthop: 172.17.0.1
        - destination: 172.17.2.0/24
          nexthop: 172.17.0.1
      attach_config: br-osp
    - name: internal_api_leaf1
      vlan: 21
      ipv4:
        cidr: 172.17.1.0/24
        allocation:
          start: 172.17.1.10
          end: 172.17.1.250
        gateway: 172.17.1.1
        routes:
        - destination: 172.17.0.0/24
          nexthop: 172.17.1.1
        - destination: 172.17.2.0/24
          nexthop: 172.17.1.1
      attach_config: br-osp
    - name: internal_api_leaf2
      vlan: 22
      ipv4:
        cidr: 172.17.2.0/24
        allocation:
          start: 172.17.2.10
          end: 172.17.2.250
        gateway: 172.17.2.1
        routes:
        - destination: 172.17.1.0/24
          nexthop: 172.17.2.1
        - destination: 172.17.0.0/24
          nexthop: 172.17.2.1
      attach_config: br-osp
  storage:
    name: Storage
    name_lower: storage
    mtu: 9000
    subnets:
    - name: storage
      vlan: 30
      ipv4:
        cidr: 172.18.0.0/24
        allocation:
          start: 172.18.0.10
          end: 172.18.0.250
        gateway: 172.18.0.1
        routes:
        - destination: 172.18.1.0/24
          nexthop: 172.18.0.1
        - destination: 172.18.2.0/24
          nexthop: 172.18.0.1
      attach_config: br-osp
    - name: storage_leaf1
      vlan: 31
      ipv4:
        cidr: 172.18.1.0/24
        allocation:
          start: 172.18.1.10
          end: 172.18.1.250
        gateway: 172.18.1.1
        routes:
        - destination: 172.18.0.0/24
          nexthop: 172.18.1.1
        - destination: 172.18.2.0/24
          nexthop: 172.18.1.1
      attach_config: br-osp
    - name: storage_leaf2
      vlan: 32
      ipv4:
        cidr: 172.18.2.0/24
        allocation:
          start: 172.18.2.10
          end: 172.18.2.250
        gateway: 172.18.2.1
        routes:
        - destination: 172.18.0.0/24
          nexthop: 172.18.2.1
        - destination: 172.18.1.0/24
          nexthop: 172.18.2.1
      attach_config: br-osp
  storagemgmt:
    name: StorageMgmt
    name_lower: storage_mgmt
    subnets:
    - name: storage_mgmt
      vlan: 40
      ipv4:
        cidr: 172.19.0.0/24
        allocation:
          start: 172.19.0.10
          end: 172.19.0.250
        gateway: 172.19.0.1
        routes:
        - destination: 172.19.1.0/24
          nexthop: 172.19.0.1
        - destination: 172.19.2.0/24
          nexthop: 172.19.0.1
      attach_config: br-osp
    - name: storage_mgmt_leaf1
      vlan: 41
      ipv4:
        cidr: 172.19.1.0/24
        allocation:
          start: 172.19.1.10
          end: 172.19.1.250
        gateway: 172.19.1.1
        routes:
        - destination: 172.19.0.0/24
          nexthop: 172.19.1.1
        - destination: 172.19.2.0/24
          nexthop: 172.19.1.1
      attach_config: br-osp
    - name: storage_mgmt_leaf2
      vlan: 42
      ipv4:
        cidr: 172.19.2.0/24
        allocation:
          start: 172.19.2.10
          end: 172.19.2.250
        gateway: 172.19.2.1
        routes:
        - destination: 172.19.0.0/24
          nexthop: 172.19.2.1
        - destination: 172.19.1.0/24
          nexthop: 172.19.2.1
      attach_config: br-osp
  tenant:
    name: Tenant
    name_lower: tenant
    vip: false
    mtu: 9000
    subnets:
    - name: tenant
      vlan: 50
      vip: false
      ipv4:
        cidr: 172.20.0.0/24
        allocation:
          start: 172.20.0.10
          end: 172.20.0.250
        gateway: 172.20.0.1
        routes:
        - destination: 172.20.1.0/24
          nexthop: 172.20.0.1
        - destination: 172.20.2.0/24
          nexthop: 172.20.0.1
      attach_config: br-osp
    - name: tenant_leaf1
      vlan: 51
      vip: false
      ipv4:
        cidr: 172.20.1.0/24
        allocation:
          start: 172.20.1.10
          end: 172.20.1.250
        gateway: 172.20.1.1
        routes:
        - destination: 172.20.0.0/24
          nexthop: 172.20.1.1
        - destination: 172.20.2.0/24
          nexthop: 172.20.1.1
      attach_config: br-osp
    - name: tenant_leaf2
      vlan: 52
      vip: false
      ipv4:
        cidr: 172.20.2.0/24
        allocation:
          start: 172.20.2.10
          end: 172.20.2.250
        gateway: 172.20.2.1
        routes:
        - destination: 172.20.0.0/24
          nexthop: 172.20.2.1
        - destination: 172.20.1.0/24
          nexthop: 172.20.2.1
      attach_config: br-osp
osp_reservations:
  openstackclient-0:
    ip_reservations:
      ctlplane: 172.22.0.251
      external: 10.0.0.251
      internal_api: 172.17.0.251
  controlplane:
    ip_reservations:
      ctlplane: 172.22.0.110
      external: 10.0.0.10
      internal_api: 172.17.0.10
      storage: 172.18.0.10
      storage_mgmt: 172.19.0.10

