---
osp_networks:
  ctlplane:
    name: Control
    name_lower: ctlplane
    is_control_plane: true
    mtu: 9000
    subnets:
    - name: ctlplane
      ipv4:
        cidr: 192.168.25.0/24
        gateway: 192.168.25.1
        allocation:
          start: 192.168.25.100
          end: 192.168.25.250
      attach_config: br-osp
  internalapi:
    name: InternalApi
    name_lower: internal_api
    subnets:
    - name: internal_api
      vlan: 20
      ipv4:
        cidr: 172.17.0.0/24
        allocation:
          start: 172.17.0.10
          end: 172.17.0.250
      attach_config: br-osp
  external:
    name: External
    name_lower: external
    subnets:
    - name: external
      ipv4:
        cidr: 10.0.0.0/24
        gateway: 10.0.0.1
        allocation:
          start: 10.0.0.10
          end: 10.0.0.250
      attach_config: br-ex
  storage:
    name: Storage
    name_lower: storage
    mtu: 9000
    subnets:
    - name: storage
      vlan: 30
      ipv4:
        cidr: 172.18.0.0/24
        allocation:
          start: 172.18.0.10
          end: 172.18.0.250
      attach_config: br-osp
  storagemgmt:
    name: StorageMgmt
    name_lower: storage_mgmt
    subnets:
    - name: storage_mgmt
      vlan: 40
      ipv4:
        cidr: 172.19.0.0/24
        allocation:
          start: 172.19.0.10
          end: 172.19.0.250
      attach_config: br-osp
  tenant:
    name: Tenant
    name_lower: tenant
    vip: false
    mtu: 9000
    subnets:
    - name: tenant
      vlan: 50
      vip: false
      ipv4:
        cidr: 172.20.0.0/24
        allocation:
          start: 172.20.0.10
          end: 172.20.0.250
      attach_config: br-osp
osp_reservations:
  openstackclient-0:
    ip_reservations:
      ctlplane: 192.168.25.251
      external: 10.0.0.251
      internal_api: 172.17.0.251
  controlplane:
    ip_reservations:
      ctlplane: 192.168.25.10
      external: 10.0.0.10
      internal_api: 172.17.0.10
      storage: 172.18.0.10
      storage_mgmt: 172.19.0.10
  controller-0:
    ip_reservations:
      ctlplane: 192.168.25.20
      external: 10.0.0.20
      internal_api: 172.17.0.20
      storage: 172.18.0.20
      storage_mgmt: 172.19.0.20
      tenant: 172.20.0.20
    mac_reservations:
      datacentre: fa:16:3a:aa:aa:aa
      datacentre2: fa:16:3b:aa:aa:aa
  controller-1:
    ip_reservations:
      ctlplane: 192.168.25.30
      external: 10.0.0.30
      internal_api: 172.17.0.30
      storage: 172.18.0.30
      storage_mgmt: 172.19.0.30
      tenant: 172.20.0.30
    macReservations:
      datacentre: fa:16:3a:aa:aa:bb
      datacentre2: fa:16:3b:aa:aa:bb
  compute-0:
    ip_reservations:
      ctlplane: 192.168.25.40
      internal_api: 172.17.0.40
      storage: 172.18.0.40
      tenant: 172.20.0.40
    macReservations:
      datacentre: fa:16:3a:bb:bb:bb
