osp_networks:
  # keeps ctlplane and tenant as ipv4
  ctlplane:
    name: Control
    name_lower: ctlplane
    is_control_plane: true
    mtu: 9000
    subnets:
    - name: ctlplane
      ipv4:
        cidr: 192.168.25.0/24
        gateway: 192.168.25.1
        allocation:
          start: 192.168.25.100
          end: 192.168.25.250
      attach_config: br-osp
  internalapi:
    name: InternalApi
    name_lower: internal_api
    subnets:
    - name: internal_api
      vlan: 20
      ipv6:
        cidr: fd00:fd00:fd00:2000::/64
        allocation:
          start: fd00:fd00:fd00:2000::10
          end: fd00:fd00:fd00:2000:ffff:ffff:ffff:fffe
      attach_config: br-osp
  external:
    name: External
    name_lower: external
    subnets:
    - name: external
      ipv6:
        cidr: 2001:db8:fd00:1000::/64
        gateway: 2001:db8:fd00:1000::1
        allocation:
          start: 2001:db8:fd00:1000::10
          end: 2001:db8:fd00:1000:ffff:ffff:ffff:fffe
      attach_config: br-ex
  storage:
    name: Storage
    name_lower: storage
    mtu: 9000
    subnets:
    - name: storage
      vlan: 30
      ipv6:
        cidr: fd00:fd00:fd00:3000::/64
        allocation:
          start: fd00:fd00:fd00:3000::10
          end: fd00:fd00:fd00:3000:ffff:ffff:ffff:fffe
      attach_config: br-osp
  storagemgmt:
    name: StorageMgmt
    name_lower: storage_mgmt
    subnets:
    - name: storage_mgmt
      vlan: 40
      ipv6:
        cidr: fd00:fd00:fd00:4000::/64
        allocation:
          start: fd00:fd00:fd00:4000::10
          end: fd00:fd00:fd00:4000:ffff:ffff:ffff:fffe
      attach_config: br-osp
  tenant:
    name: Tenant
    name_lower: tenant
    vip: false
    mtu: 9000
    subnets:
    - name: tenant
      vlan: 50
      vip: false
      ipv4:
        cidr: 172.20.0.0/24
        allocation:
          start: 172.20.0.10
          end: 172.20.0.250
      attach_config: br-osp
osp_reservations:
  openstackclient-0:
    ip_reservations:
      ctlplane: 192.168.25.251
      external: 2001:db8:fd00:1000::251
      internal_api: fd00:fd00:fd00:2000::251
  controlplane:
    ip_reservations:
      ctlplane: 192.168.25.10
      external: 2001:db8:fd00:1000::10
      internal_api: fd00:fd00:fd00:2000::10
      storage: fd00:fd00:fd00:3000::10
      storage_mgmt: fd00:fd00:fd00:4000::10
  controller-0:
    ip_reservations:
      ctlplane: 192.168.25.20
      external: 2001:db8:fd00:1000::20
      internal_api: fd00:fd00:fd00:2000::20
      storage: fd00:fd00:fd00:3000::20
      storage_mgmt: fd00:fd00:fd00:4000::20
      tenant: 172.20.0.20
    mac_reservations:
      datacentre: fa:16:3a:aa:aa:aa
      datacentre2: fa:16:3b:aa:aa:aa
  controller-1:
    ip_reservations:
      ctlplane: 192.168.25.30
      external: 2001:db8:fd00:1000::30
      internal_api: fd00:fd00:fd00:2000::30
      storage: fd00:fd00:fd00:3000::30
      storage_mgmt: fd00:fd00:fd00:4000::30
      tenant: 172.20.0.30
    macReservations:
      datacentre: fa:16:3a:aa:aa:bb
      datacentre2: fa:16:3b:aa:aa:bb
  compute-0:
    ip_reservations:
      ctlplane: 192.168.25.40
      internal_api: fd00:fd00:fd00:2000::40
      storage: fd00:fd00:fd00:3000::40
      tenant: 172.20.0.40
    macReservations:
      datacentre: fa:16:3a:bb:bb:bb
