---
openstackclient_image: quay.io/tripleotraincentos8/centos-binary-tripleoclient:current-tripleo
openstackclient_networks:
  - ctlplane
  - external
  - internal_api
  - internal_api_leaf1

ephemeral_heat:
  heat_api_image: quay.io/tripleotraincentos8/centos-binary-heat-api:current-tripleo
  heat_engine_image: quay.io/tripleotraincentos8/centos-binary-heat-engine:current-tripleo
  mariadb_image: quay.io/tripleotraincentos8/centos-binary-mariadb:current-tripleo
  rabbit_image: quay.io/tripleotraincentos8/centos-binary-rabbitmq:current-tripleo

osp_release_defaults:
  release: train
  container_tag: current-tripleo
  base_image_url: https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20230404.0.x86_64.qcow2
  #TODO: which ceph images tag to use for upstream train?
  #ceph_tag: 5-12
  #ceph_image: daemon
  networks: ipv4_subnet
  vmset:
    Controller:
      count: 1
      cores: 6
      memory: 20
      networks:
        - ctlplane
        - internal_api
        - external
        - tenant
        - storage
        - storage_mgmt
      root_disk:
        disk_size: 40
        storage_class: host-nfs-storageclass
        storage_access_mode: ReadWriteMany
        storage_volume_mode: Filesystem
  bmset:
    Compute:
      count: 0
    ComputeLeaf1:
      count: 1
      ctlplane_interface: enp1s0
      networks:
        - ctlplane
        - internal_api_leaf1
        - tenant_leaf1
        - storage_leaf1
    ComputeLeaf2:
      count: 1
      ctlplane_interface: enp1s0
      networks:
        - ctlplane
        - internal_api_leaf2
        - tenant_leaf2
        - storage_leaf2
