#!/usr/bin/env ansible-playbook
---
- name: DataVolume Cleanup
  hosts: localhost
  vars_files: "vars/default.yaml"
  roles:
    - oc_local

  tasks:
    - name: Set combined osp dict
      ansible.builtin.set_fact:
        osp: "{{ osp_defaults | combine((osp_release_defaults | default({})), recursive=True) | combine((osp_local | default({})), recursive=True) }}"

    - name: Delete base image {{ osp.base_image_url | basename }}
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "{{ base_path }}/ironic/html/images/*.qcow2"

    - name: Check assisted installer image directory
      become: true
      become_user: root
      ansible.builtin.stat:
        path: /opt/http_store/data/images
      register: assisted_installer_image_dir

    - name: Find assisted installer base images
      become: true
      become_user: root
      when: assisted_installer_image_dir.stat.exists
      ansible.builtin.find:
        paths: /opt/http_store/data/images
        patterns: "*.qcow2"
        file_type: file
        recurse: false
      register: assisted_installer_images

    - name: Delete assisted installer base images
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ assisted_installer_images.files | default([]) }}"

    - name: Delete all datavolumes and base image PVC
      ansible.builtin.shell: |
        oc delete dv --all -n {{ namespace }}
        oc delete pvc controller-base-img --ignore-not-found -n {{ namespace }}
      environment: &oc_env
        PATH: "{{ oc_env_path }}"
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Delete provionserver
      ansible.builtin.shell: |
        oc delete openstackprovisionservers.osp-director.openstack.org --ignore-not-found=true openstack -n {{ namespace }}
      environment:
        <<: *oc_env
