#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars_files: "vars/default.yaml"
  roles:
  - oc_local

  tasks:

  - name: Set opm download url suffix
    set_fact: opm_url_suffix="latest/download"
    when: opm_version is undefined or opm_version == "latest"

  - name: Set opm download url suffix
    set_fact: opm_url_suffix="download/{{ opm_version }}"
    when: opm_version is defined and opm_version != "latest"

  - name: Create $HOME/bin dir
    file:
      path: "{{ lookup('env', 'HOME') }}/bin"
      state: directory
      mode: '0755'

  - name: Download opm
    get_url:
      url: https://github.com/operator-framework/operator-registry/releases/{{ opm_url_suffix }}/linux-amd64-opm
      dest: "{{ lookup('env', 'HOME') }}/bin/opm"
      mode: '0755'
      timeout: 30

  - name: Download operator-sdk
    get_url:
      url: https://github.com/operator-framework/operator-sdk/releases/download/{{ sdk_version }}/operator-sdk_linux_amd64
      dest: "{{ lookup('env', 'HOME') }}/bin/operator-sdk"
      mode: '0755'
      timeout: 30

  - name: Download and extract kustomize
    unarchive:
      src: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F{{ kustomize_version }}/kustomize_{{ kustomize_version }}_linux_amd64.tar.gz
      dest: "{{ lookup('env', 'HOME') }}/bin/"
      remote_src: yes

  - name: Download kuttl
    get_url:
      url: https://github.com/kudobuilder/kuttl/releases/download/v{{ kuttl_version }}/kubectl-kuttl_{{ kuttl_version }}_linux_x86_64
      dest: "{{ lookup('env', 'HOME') }}/bin/kubectl-kuttl"
      mode: '0755'
      timeout: 30

  - name: Install packages
    become: true
    become_user: root
    package:
      state: installed
      name:
        - golang
