---
- hosts: convergence_base
  become: true
  become_user: ocp

  tasks:
  - name: Include variables
    include_vars: vars/default.yaml

  - name: Clean dev-scripts deployment
    shell: |
      export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
      make clean
    args:
      chdir: "{{ base_path }}/dev-scripts"

  ### remove osp_controller_base_image

  - name: Set path to RHEL base image for dev-scripts
    set_fact:
      osp_controller_base_image_url_path: "{{ base_path }}/ironic/html/images/{{ osp_controller_base_image_url | basename }}"

  - name: Delete {{ osp_controller_base_image_url_path }}
    file:
      path: "{{ osp_controller_base_image_url_path }}"
      state: absent
