---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
    - oc_local

  tasks:
    - name: Set combined osp dict
      set_fact:
        osp: "{{ osp_defaults | combine((osp_release_defaults | default({})), recursive=True) | combine((osp_local | default({})), recursive=True) }}"

    - name: set deletePolicy=Newest on existing worker machineset for predictable scale down
      shell: >
        oc get -n openshift-machine-api machineset -l machine.openshift.io/cluster-api-machine-type=worker -o json | jq '.spec.deletePolicy="Newest"' | oc apply -f -
      environment: &oc_env
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
        KUBECONFIG: "{{ base_path }}/dev-scripts/ocp/{{ ocp_cluster_name }}/auth/kubeconfig"

    - name: get number of ready OCP baremetal nodes
      shell: >
        echo $(oc get -n openshift-machine-api baremetalhost | grep worker |grep ready | wc -l)
      environment:
        <<: *oc_env
      register: worker_ocp_ready

    - name: scale down OCP workers if there are not enough ready baremetal nodes
      when:
        - osp.compute.count > 0
        - worker_ocp_ready.stdout|int != osp.compute.count|int
      block:
        - name: get current {{ ocp_cluster_name }}-worker-0 replicas
          shell: >
            oc -n openshift-machine-api get machineset -l machine.openshift.io/cluster-api-machine-type=worker -o json | jq -r .items[0].status.replicas
          environment:
            <<: *oc_env
          register: worker_replicas

        - name: set fact of new replicas count
          set_fact:
            replicas: "{{ worker_replicas.stdout|int - osp.compute.count|int }}"

        - name: scale down worker machineset by {{ replicas }}
          shell: >
            oc -n openshift-machine-api scale machineset -l machine.openshift.io/cluster-api-machine-type=worker --replicas={{ replicas }}
          environment:
            <<: *oc_env

        - name: wait until worker got deprovisioned
          shell: >
            echo $(oc get -n openshift-machine-api baremetalhost | grep worker |grep ready | wc -l)
          environment:
            <<: *oc_env
          register: worker_ocp_ready
          until: worker_ocp_ready.stdout|int == osp.compute.count|int
          delay: 30
          retries: 60
