---
- hosts: localhost
  vars_files: vars/default.yaml
  roles:
  - oc_local

  tasks:
    - name:
      include_tasks: osp_sts.yaml
      vars:
          sts_script : 'osp_operator_workload_vm_run.sh'

# stf tests section
    - name: Clone stf tests
      shell: |
        #!/bin/bash
        oc exec -n openstack openstackclient -- bash -c "test -d /home/cloud-admin/functional-tests || (pushd /home/cloud-admin/ && git clone -c http.sslVerify=false https://github.com/infrawatch/functional-tests.git)"

    - name: Create playbooks directory
      shell: |
       #!/bin/bash
       oc exec -n openstack openstackclient -- bash -c "test -d /home/cloud-admin/playbooks/ || mkdir /home/cloud-admin/playbooks/"
    - name: Download jumphost key file
      shell: |
       #!/bin/bash
       oc exec -n openstack openstackclient -- bash -c "curl --insecure  {{ DEVTOOLS_STF_JUMPHOST_KEY_URL }} --output /home/cloud-admin/playbooks/jumphost.key;chmod 600 /home/cloud-admin/playbooks/jumphost.key"
    - name: Create public network
      shell: >
        #!/bin/bash
        oc exec -n openstack openstackclient -- bash -c "openstack network list |grep public || openstack network create --external --provider-network-type flat --provider-physical-network datacentre public &&
        openstack subnet create public --subnet-range 10.0.0.0/24 --allocation-pool start=10.0.0.200,end=10.0.0.250 --dns-nameserver 10.46.0.31 --network public &&
        openstack router create router &&
        openstack router set router --external-gateway public &&
        openstack network list --external"
    - name: Run stf tests
      vars:
        ir_tripleo_overcloud_templates: 'custom-stf-ceph,stf-connectors-osp17.0,gnocchi-connectors-rbd,ceph-single-host-mode'
      shell: |
        #!/bin/bash
        oc exec -n openstack openstackclient -- bash -c "pushd /home/cloud-admin/ && ANSIBLE_CALLBACK_WHITELIST=custom_logger ansible-playbook -i /home/cloud-admin/functional-tests/default.inv /home/cloud-admin/functional-tests/stf_functional_tests.yml" --tags {{ ir_tripleo_overcloud_templates }},OSP17.1
