---
- name: Copy pull-secret file
  when: secrets_repo is undefined
  block:
  - name: Set secrets repo path
    set_fact:
      secrets_repo_path: "{{ base_path }}"

  - name: Copy pull-secret
    copy:
      dest: "{{ base_path }}/pull-secret"
      src: files/pull-secret
      mode: "0644"
  rescue:
  - name: Fail when pull-secrets is not found
    fail:
      msg: |
        files/pull-secret is not present. You must obtain it from
        https://cloud.redhat.com/openshift/install/pull-secret and copy it
        there manually.

- name: use secrets_repo
  when: secrets_repo is defined
  block:
  - name: Set secrets_repo path
    set_fact:
      secrets_repo_path: "{{ base_path }}/{{ secrets_repo | urlsplit('hostname') }}/{{ (secrets_repo | urlsplit('path') | splitext)[0] }}"

  - name: create base dir for secrets_repo repo
    file:
      path: "{{ secrets_repo_path }}"
      state: directory
      mode: "0755"

  - name: Clone the repo specified in secrets_repo
    git:
      repo: "{{ secrets_repo }}"
      dest: "{{ secrets_repo_path }}"
      version: "{{ secrets_branch | default('HEAD', true) }}"
    environment:
      GIT_SSL_NO_VERIFY: "true"
