# Based on https://github.com/marketplace/actions/ansible-lint
name: Ansible lint github pipeline

on: [push, pull_request]

jobs:
  test:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Lint Ansible Playbooks
        uses: ansible/ansible-lint@06f616d6e86e9ce4c74393318d1cbb2d016af413 # v25.6.1
        with:
          requirements_file: ansible/requirements.yml
