# Based on https://github.com/marketplace/actions/ansible-lint
name: Ansible lint github pipeline

on: [push, pull_request]

jobs:
  test:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Lint Ansible Playbooks
        uses: ansible/ansible-lint@a2bc8b8b13a80802215856c56823d85007d3baf5 # v25.12.2
        with:
          requirements_file: ansible/requirements.yml
